services:
  postgres:
    image: postgres:15
    container_name: userstory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: userstory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  backend:
    build: .
    container_name: userstory_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "3008:3008"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
